### ISSUE TITLE
[Request] Migrate Django old version to New one

### ISSUE THREAD

**Issue by Aju100** [Code4Nepal/mero-book#15]
Hi @ravinepal and @amitness, the codebase of this mero-book project is an outdated version of Django. I am interested in migrating this project to the newer one. 

The impacts of the migration are the following.
- Increased security (Patches on many CVE of the older version).
- Ensured support for future growth.

Moreover, my future work itineraries are enlisted below. 
- Containerize mero-book.
- Refactor codebase (Linting, PEP8, Optimization).
- New Design (Frontend).
- Unit testing.
- Improve documentation for better comprehension.
- Asynchronous (Event-based architecture).

**Comment by ravinepal** [comment]
hi aju -- thanks for your interest. we are no longer maintaining this product. we'd be very grateful for your support on our NepalMap product, especially the blog section that @ishandongol is currently leading: https://github.com/CodeforNepal/nepalmap_blog

**Comment by Aju100** [comment]
Hi @ravinepal ,

Thank you for your response regarding this issue. As I am most familiar with python, I would love to contribute to the nepalmap_blog project with beginner-friendly issues.

Regards, 
Aju Tamang

**Comment by ishandongol** [comment]
Hi aju,
If that's the case then you can contribute to nepalmap_federal which is in
django and wazimap. We need to upgrade django and wazimap.

**Comment by Aju100** [comment]
Hi @ishandongol , 

I would be working on it by creating a new branch. Thank you

Regards,
Aju Tamang
